import React, { createContext, useContext, useState, ReactNode } from "react";

export interface LanguageOption {
  code: string;
  name: string;
  native: string;
  flag: string;
}

export const supportedLanguages: LanguageOption[] = [
  { code: "en", name: "English", native: "English", flag: "🇺🇸" },
  { code: "te", name: "Telugu", native: "తెలుగు", flag: "🇮🇳" },
  { code: "hi", name: "Hindi", native: "हिन्दी", flag: "🇮🇳" },
  { code: "ta", name: "Tamil", native: "தமிழ்", flag: "🇮🇳" },
  { code: "kn", name: "Kannada", native: "ಕನ್ನಡ", flag: "🇮🇳" },
  { code: "ml", name: "Malayalam", native: "മലയാളം", flag: "🇮🇳" },
  { code: "mr", name: "Marathi", native: "मराठी", flag: "🇮🇳" },
  { code: "gu", name: "Gujarati", native: "ગુજરાતી", flag: "🇮🇳" },
  { code: "bn", name: "Bengali", native: "বাংলা", flag: "🇮🇳" },
  { code: "es", name: "Spanish", native: "Español", flag: "🇪🇸" },
  { code: "fr", name: "French", native: "Français", flag: "🇫🇷" },
  { code: "de", name: "German", native: "Deutsch", flag: "🇩🇪" },
];

export const globalTranslations: Record<string, Record<string, string>> = {
  en: {
    // Nav & Layout
    dashboard: "Dashboard",
    smartMirror: "Smart Mirror",
    dentalChat: "Dr. Minty AI Chat",
    profile: "Profile Settings",
    signOut: "Sign Out / Logout",
    proPlan: "Pro Plan Active",
    selectLanguage: "Select Language",

    // Demographics Screen
    demographicsTitle: "Tell us about yourself",
    demographicsSubtitle: "Help us personalize your dental care experience",
    fullNameLabel: "Full Name",
    fullNamePlaceholder: "Enter your name",
    ageGroupLabel: "Age Group",
    selectAgeGroup: "Select age group",
    childMode: "Under 12 (Child Mode)",
    teenMode: "13-17 (Teenager)",
    adultMode: "18-59 (Adult Mode)",
    seniorMode: "60+ (Senior Mode)",
    genderLabel: "Gender",
    male: "Male",
    female: "Female",
    other: "Other",
    continueBtn: "Continue",
    savingProfile: "Saving Profile...",
    step1of3: "Step 1 of 3",

    // Assessment Screen
    assessmentTitle: "Oral Health Assessment",
    question: "Question",
    of: "of",
    completed: "Completed",
    nextQuestion: "Next Question",
    prevQuestion: "Previous",
    viewResults: "View Clinical Results",

    // Prescription Screen
    personalizedResult: "Personalized Clinical Result",
    careStrategy: "Tailored Care Strategy",
    prescriptionSummaryTitle: "Clinical Prescription Summary",
    whySuggestedTitle: "Why this technique was suggested for your teeth",
    basedOnAnswers: "Based on your 10 assessment answers:",
    whatIsItTitle: "What is that technique?",
    howItWorksTitle: "How the technique works",
    precautionsTitle: "Precautions & Clinical Safety Tips",
    videoGuideTitle: "Video Demonstration Guide & Clinical Motion Simulator",
    videoSubtitle: "Watch the official clinical video demonstration of your prescribed technique.",
    stepsTitle: "Prescribed Step-by-Step Brushing Guide",
    step: "Step",
    bestPracticeTitle: "Clinical Best Practice",
    bestPracticeDesc: "Brush for 2 minutes twice a day (morning and night) using your prescribed technique.",
    startMirrorBtn: "Start Guided Smart Mirror Session",
    returnDashboardBtn: "Return to Dashboard",

    // Dashboard
    welcomeBack: "Welcome back",
    brushingStreak: "Brushing Streak",
    daysStreak: "Days Streak",
    totalSessions: "Total Brushing Sessions",
    weeklyCompliance: "Weekly Compliance",
    morningRoutine: "☀️ Morning Routine",
    nightRoutine: "🌙 Night Routine",
    saveReminders: "Save Active Reminder Times",
    retakeQuiz: "Retake Assessment Questionnaire",

    // Profile & Chat
    editProfile: "Edit Profile Details",
    askPlaceholder: "Ask Dr. Minty about tooth sensitivity, brushing or toothpaste...",
    quickQuestions: "Quick questions:",
    onlineStatus: "Online - Virtual Dental Assistant"
  },

  te: {
    // Nav & Layout
    dashboard: "డాష్‌బోర్డ్",
    smartMirror: "స్మార్ట్ మిర్రర్",
    dentalChat: "డాక్టర్ మింటీ ఏఐ చాట్",
    profile: "ప్రొఫైల్ సెట్టింగ్‌లు",
    signOut: "లాగ్ అవుట్ చేయండి",
    proPlan: "ప్రో ప్లాన్ సక్రియం",
    selectLanguage: "భాషను ఎంచుకోండి",

    // Demographics Screen
    demographicsTitle: "మీ గురించి మాకు చెప్పండి",
    demographicsSubtitle: "మీ దంత సంరక్షణ అనుభవాన్ని వ్యక్తిగతీకరించడంలో మాకు సహాయపడండి",
    fullNameLabel: "పూర్తి పేరు",
    fullNamePlaceholder: "మీ పేరును నమోదు చేయండి",
    ageGroupLabel: "వయో సమూహం",
    selectAgeGroup: "వయో సమూహాన్ని ఎంచుకోండి",
    childMode: "12 సంవత్సరాల లోపు (పిల్లల మోడ్)",
    teenMode: "13-17 (టీనేజర్)",
    adultMode: "18-59 (వయోజన మోడ్)",
    seniorMode: "60+ (సీనియర్ మోడ్)",
    genderLabel: "లింగం",
    male: "పురుషుడు",
    female: "స్త్రీ",
    other: "ఇతర",
    continueBtn: "కొనసాగించండి",
    savingProfile: "ప్రొఫైల్ సేవ్ చేయబడుతోంది...",
    step1of3: "3 లో 1 వ దశ",

    // Assessment Screen
    assessmentTitle: "నోటి ఆరోగ్య అసెస్మెంట్",
    question: "ప్రశ్న",
    of: "లో",
    completed: "పూర్తయింది",
    nextQuestion: "తరువాతి ప్రశ్న",
    prevQuestion: "క్రితం",
    viewResults: "క్లినికల్ ఫలితాలను చూడండి",

    // Prescription Screen
    personalizedResult: "వ్యక్తిగతీకరించిన క్లినికల్ ఫలితం",
    careStrategy: "అనుకూలీకరించిన సంరక్షణ వ్యూహం",
    prescriptionSummaryTitle: "క్లినికల్ ప్రిస్క్రిప్షన్ సారాంశం",
    whySuggestedTitle: "మీ పళ్ళకు ఈ పద్ధతి ఎందుకు సూచించబడింది",
    basedOnAnswers: "మీ 10 అసెస్మెంట్ సమాధానాల ఆధారంగా:",
    whatIsItTitle: "ఈ పద్ధతి అంటే ఏమిటి?",
    howItWorksTitle: "ఈ పద్ధతి ఎలా పనిచేస్తుంది",
    precautionsTitle: "ముందు జాగ్రత్తలు & సేఫ్టీ చిట్కాలు",
    videoGuideTitle: "వీడియో డెమోన్స్ట్రేషన్ గైడ్ & మోషన్ సిమ్యులేటర్",
    videoSubtitle: "మీకు సూచించిన బ్రషింగ్ పద్ధతి యొక్క అధికారిక క్లినికల్ వీడియో చూడండి.",
    stepsTitle: "సూచించిన దశల వారీ బ్రషింగ్ మార్గదర్శి",
    step: "దశ",
    bestPracticeTitle: "క్లినికల్ ఉత్తమ అభ్యాసం",
    bestPracticeDesc: "మీకు సూచించిన పద్ధతిని ఉపయోగించి రోజుకు రెండుసార్లు (ఉదయం మరియు రాత్రి) 2 నిమిషాలు బ్రష్ చేయండి.",
    startMirrorBtn: "గైడెడ్ స్మార్ట్ మిర్రర్ ప్రారంభించండి",
    returnDashboardBtn: "డాష్‌బోర్డ్‌కు తిరిగెళ్ళండి",

    // Dashboard
    welcomeBack: "తిరిగి స్వాగతం",
    brushingStreak: "బ్రషింగ్ స్ట్రీక్",
    daysStreak: "రోజుల వరుస",
    totalSessions: "మొత్తం బ్రషింగ్ సెషన్లు",
    weeklyCompliance: "వారపు సమ్మతి",
    morningRoutine: "☀️ ఉదయం దినచర్య",
    nightRoutine: "🌙 రాత్రి దినచర్య",
    saveReminders: "రిమైండర్ సమయాలను సేవ్ చేయండి",
    retakeQuiz: "అసెస్మెంట్ క్విజ్ మళ్ళీ తీసుకోండి",

    // Profile & Chat
    editProfile: "ప్రొఫైల్ వివరాలను సవరించండి",
    askPlaceholder: "సున్నితత్వం, టూత్‌పేస్ట్ లేదా బ్రషింగ్ గురించి అడగండి...",
    quickQuestions: "త్వరిత ప్రశ్నలు:",
    onlineStatus: "ఆన్‌లైన్ - వర్చువల్ అసిస్టెంట్"
  },

  hi: {
    // Nav & Layout
    dashboard: "डैशबोर्ड",
    smartMirror: "स्मार्ट मिरर",
    dentalChat: "डॉ. मिंटी एआई चैट",
    profile: "प्रोफ़ाइल सेटिंग्स",
    signOut: "साइन आउट / लॉगआउट",
    proPlan: "प्रो प्लान सक्रिय",
    selectLanguage: "भाषा चुनें",

    // Demographics Screen
    demographicsTitle: "अपने बारे में बताएं",
    demographicsSubtitle: "अपने दंत देखभाल अनुभव को व्यक्तिगत बनाने में मदद करें",
    fullNameLabel: "पूरा नाम",
    fullNamePlaceholder: "अपना नाम दर्ज करें",
    ageGroupLabel: "आयु वर्ग",
    selectAgeGroup: "आयु वर्ग चुनें",
    childMode: "12 से कम (चाइल्ड मोड)",
    teenMode: "13-17 (किशोरी)",
    adultMode: "18-59 (वयस्क मोड)",
    seniorMode: "60+ (वरिष्ठ नागरिक)",
    genderLabel: "लिंग",
    male: "पुरुष",
    female: "महिला",
    other: "अन्य",
    continueBtn: "जारी रखें",
    savingProfile: "प्रोफ़ाइल सहेजी जा रही है...",
    step1of3: "चरण 1 का 3",

    // Assessment Screen
    assessmentTitle: "मौखिक स्वास्थ्य मूल्यांकन",
    question: "प्रश्न",
    of: "का",
    completed: "पूरा हुआ",
    nextQuestion: "अगला प्रश्न",
    prevQuestion: "पिछला",
    viewResults: "नैदानिक परिणाम देखें",

    // Prescription Screen
    personalizedResult: "व्यक्तिगत नैदानिक परिणाम",
    careStrategy: "अनुकूलित देखभाल रणनीति",
    prescriptionSummaryTitle: "नैदानिक नुस्खा सारांश",
    whySuggestedTitle: "आपके दांतों के लिए यह तकनीक क्यों सुझाई गई",
    basedOnAnswers: "आपके 10 मूल्यांकन उत्तरों के आधार पर:",
    whatIsItTitle: "वह तकनीक क्या है?",
    howItWorksTitle: "तकनीक कैसे काम करती है",
    precautionsTitle: "सावधानियां और सुरक्षा सुझाव",
    videoGuideTitle: "वीडियो प्रदर्शन गाइड और मोशन सिमुलेटर",
    videoSubtitle: "अपनी निर्धारित तकनीक का आधिकारिक वीडियो प्रदर्शन देखें।",
    stepsTitle: "निर्धारित चरण-दर-चरण ब्रशिंग गाइड",
    step: "चरण",
    bestPracticeTitle: "नैदानिक सर्वोत्तम अभ्यास",
    bestPracticeDesc: "अपनी निर्धारित तकनीक का उपयोग करके दिन में दो बार 2 मिनट के लिए ब्रश करें।",
    startMirrorBtn: "गाइडेड स्मार्ट मिरर शुरू करें",
    returnDashboardBtn: "डैशबोर्ड पर लौटें",

    // Dashboard
    welcomeBack: "वापसी पर आपका स्वागत है",
    brushingStreak: "ब्रशिंग स्ट्राइक",
    daysStreak: "दिनों की लकीर",
    totalSessions: "कुल ब्रशिंग सत्र",
    weeklyCompliance: "साप्ताहिक अनुपालन",
    morningRoutine: "☀️ सुबह की दिनचर्या",
    nightRoutine: "🌙 रात की दिनचर्या",
    saveReminders: "रिमाइंडर समय सहेजें",
    retakeQuiz: "मूल्यांकन प्रश्नावली फिर से लें",

    // Profile & Chat
    editProfile: "प्रोफ़ाइल विवरण संपादित करें",
    askPlaceholder: "दांतों की संवेदनशीलता या टूथपेस्ट के बारे में पूछें...",
    quickQuestions: "त्वरित प्रश्न:",
    onlineStatus: "ऑनलाइन - वर्चुअल असिस्टेंट"
  },

  ta: {
    dashboard: "டாஷ்போர்டு",
    smartMirror: "ஸ்மார்ட் கண்ணாடி",
    dentalChat: "டாக்டர் மிண்டி AI அரட்டை",
    profile: "சுயவிவர அமைப்புகள்",
    signOut: "வெளியேறு",
    proPlan: "ப்ரோ திட்டம் செயலில் உள்ளது",
    selectLanguage: "மொழியைத் தேர்ந்தெடுக்கவும்",
    demographicsTitle: "உங்களைப் பற்றிச் சொல்லுங்கள்",
    demographicsSubtitle: "உங்கள் பல் பராமரிப்பு அனுபவத்தைத் தனிப்பயனாக்க உதவுங்கள்",
    fullNameLabel: "முழு பெயர்",
    fullNamePlaceholder: "உங்கள் பெயரை உள்ளிடவும்",
    ageGroupLabel: "வயதுக் குழு",
    selectAgeGroup: "வயதுக் குழுவைத் தேர்ந்தெடுக்கவும்",
    childMode: "12 வயதுக்குட்பட்ட (குழந்தை பயன்முறை)",
    teenMode: "13-17 (இளைஞர்)",
    adultMode: "18-59 (பெரியவர் பயன்முறை)",
    seniorMode: "60+ (மூத்த குடிமகன்)",
    genderLabel: "பாலினம்",
    male: "ஆண்",
    female: "பெண்",
    other: "மற்றவை",
    continueBtn: "தொடரவும்",
    savingProfile: "சேமிக்கப்படுகிறது...",
    step1of3: "படி 1/3",
    assessmentTitle: "வாய்வழி சுகாதார மதிப்பீடு",
    question: "கேள்வி",
    of: "இல்",
    completed: "நிறைவடைந்தது",
    nextQuestion: "அடுத்த கேள்வி",
    prevQuestion: "முந்தைய",
    viewResults: "முடிவுகளைக் காண்க",
    personalizedResult: "தனிப்பயனாக்கப்பட்ட முடிவு",
    prescriptionSummaryTitle: "சிகிச்சை சுருக்கம்",
    whySuggestedTitle: "இந்த முறை ஏன் பரிந்துரைக்கப்பட்டது",
    basedOnAnswers: "உங்கள் பதில்களின் அடிப்படையில்:",
    whatIsItTitle: "இந்த முறை என்ன?",
    howItWorksTitle: "இந்த முறை எப்படி வேலை செய்கிறது",
    precautionsTitle: "முன்னெச்சரிக்கைகள் & பாதுகாப்பு குறிப்புகள்",
    videoGuideTitle: "வீடியோ செயல்முறை வழிகாட்டி",
    stepsTitle: "படி-படியாக துலக்கும் வழிகாட்டி",
    step: "படி",
    bestPracticeTitle: "சிறந்த சிகிச்சை முறை",
    bestPracticeDesc: "பரிந்துரைக்கப்பட்ட முறையைப் பயன்படுத்தி தினமும் இருமுறை 2 நிமிடங்கள் பல் துலக்கவும்.",
    startMirrorBtn: "ஸ்மார்ட் கண்ணாடியைத் தொடங்குங்கள்",
    returnDashboardBtn: "டாஷ்போர்டிற்குத் திரும்பு",
    welcomeBack: "மீண்டும் வருக",
    brushingStreak: "துலக்குதல் தொடர்",
    daysStreak: "நாட்கள் தொடர்",
    totalSessions: "மொத்த அமர்வுகள்",
    weeklyCompliance: "வாராந்திர இணக்கம்",
    morningRoutine: "☀️ காலை வழக்கம்",
    nightRoutine: "🌙 இரவு வழக்கம்",
    saveReminders: "நினைவூட்டலைச் சேமிக்கவும்",
    retakeQuiz: "மதிப்பீட்டை மீண்டும் எடுக்கவும்",
    editProfile: "சுயவிவரத்தைத் திருத்து",
    askPlaceholder: "பல் கூச்சம் அல்லது பேஸ்ட் பற்றி கேட்கவும்...",
    quickQuestions: "விரைவு கேள்விகள்:",
    onlineStatus: "ஆன்லைன் உதவியாளர்"
  },

  kn: {
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    smartMirror: "ಸ್ಮಾರ್ಟ್ ಮಿರರ್",
    dentalChat: "ಡಾ. ಮಿಂಟಿ ಎಐ ಚಾಟ್",
    profile: "ಪ್ರೊಫೈಲ್ ಸಂಯೋಜನೆಗಳು",
    signOut: "ಸೈನ್ ಔಟ್",
    selectLanguage: "ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    demographicsTitle: "ನಿಮ್ಮ ಬಗ್ಗೆ ನಮಗೆ ತಿಳಿಸಿ",
    demographicsSubtitle: "ನಿಮ್ಮ ದಂತ ಆರೈಕೆ ಅನುಭವವನ್ನು ವೈಯಕ್ತಿಕಗೊಳಿಸಲು ನಮಗೆ ಸಹಾಯ ಮಾಡಿ",
    fullNameLabel: "ಪೂರ್ಣ ಹೆಸರು",
    fullNamePlaceholder: "ನಿಮ್ಮ ಹೆಸರನ್ನು ನಮೂದಿಸಿ",
    ageGroupLabel: "ವಯಸ್ಸಿನ ಗುಂಪು",
    selectAgeGroup: "ವಯಸ್ಸಿನ ಗುಂಪನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    childMode: "12 ರ ಕೆಳಗೆ (ಮಕ್ಕಳ ಮೋಡ್)",
    teenMode: "13-17 (ಹದಿಹರೆಯದವರು)",
    adultMode: "18-59 (ವಯಸ್ಕ ಮೋಡ್)",
    seniorMode: "60+ (ಹಿರಿಯರು)",
    genderLabel: "ಲಿಂಗ",
    male: "ಪುರುಷ",
    female: "ಮಹಿಳೆ",
    other: "ಇತರ",
    continueBtn: "ಮುಂದುವರಿಸಿ",
    savingProfile: "ಉಳಿಸಲಾಗುತ್ತಿದೆ...",
    step1of3: "ಹಂತ 1 ರಲ್ಲಿ 3",
    assessmentTitle: "ಮೌಖಿಕ ಆರೋಗ್ಯ ಮೌಲ್ಯಮಾಪನ",
    question: "ಪ್ರಶ್ನೆ",
    of: "ರ",
    completed: "ಪೂರ್ಣಗೊಂಡಿದೆ",
    nextQuestion: "ಮುಂದಿನ ಪ್ರಶ್ನೆ",
    prevQuestion: "ಹಿಂದಿನ",
    viewResults: "ಫಲಿತಾಂಶಗಳನ್ನು ವೀಕ್ಷಿಸಿ",
    personalizedResult: "ವೈಯಕ್ತಿಕಗೊಳಿಸಿದ ವೈದ್ಯಕೀಯ ಫಲಿತಾಂಶ",
    prescriptionSummaryTitle: "ವೈದ್ಯಕೀಯ ಸೂಚನಾ ಸಾರಾಂಶ",
    whySuggestedTitle: "ನಿಮ್ಮ ಹಲ್ಲುಗಳಿಗೆ ಈ ವಿಧಾನವನ್ನು ಏಕೆ ಸೂಚಿಸಲಾಗಿದೆ",
    basedOnAnswers: "ನಿಮ್ಮ 10 ಉತ್ತರಗಳ ಆಧಾರದ ಮೇಲೆ:",
    whatIsItTitle: "ಆ ವಿಧಾನ ಎಂದರೇನು?",
    howItWorksTitle: "ವಿಧಾನವು ಹೇಗೆ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ",
    precautionsTitle: "ಮುನ್ನೆಚ್ಚರಿಕೆಗಳು ಮತ್ತು ಸುರಕ್ಷತಾ ಸುಳಿವುಗಳು",
    videoGuideTitle: "ವೀಡಿಯೊ ಪ್ರಾತ್ಯಕ್ಷಿಕೆ ಮಾರ್ಗದರ್ಶಿ",
    stepsTitle: "ಹಂತ ಹಂತದ ಬ್ರಶಿಂಗ್ ಮಾರ್ಗದರ್ಶಿ",
    step: "ಹಂತ",
    bestPracticeTitle: "ಉತ್ತಮ ಅಭ್ಯಾಸ",
    bestPracticeDesc: "ದಿನಕ್ಕೆ 2 ಬಾರಿ 2 ನಿಮಿಷಗಳ ಕಾಲ ಬ್ರಷ್ ಮಾಡಿ.",
    startMirrorBtn: "ಸ್ಮಾರ್ಟ್ ಮಿರರ್ ಪ್ರಾರಂಭಿಸಿ",
    returnDashboardBtn: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ආಪﺲ ಬನ್ನಿ",
    welcomeBack: "ಮತ್ತೆ ಸ್ವಾಗತ",
    brushingStreak: "ಬ್ರಶಿಂಗ್ ಸ್ಟ್ರೀಕ್",
    daysStreak: "ದಿನಗಳ ಸರಣಿ",
    totalSessions: "ಒಟ್ಟು ಸೆಷನ್‌ಗಳು",
    weeklyCompliance: "ವಾರದ ಅನುಸರಣೆ",
    morningRoutine: "☀️ ಬೆಳಗಿನ ದಿನಚರಿ",
    nightRoutine: "🌙 ರಾತ್ರಿಯ ದಿನಚರಿ",
    saveReminders: "ಸಮಯವನ್ನು ಉಳಿಸಿ",
    retakeQuiz: "ರಸಪ್ರಶ್ನೆಯನ್ನು ಮತ್ತೆ ತೆಗೆದುಕೊಳ್ಳಿ",
    editProfile: "ವಿವರಗಳನ್ನು ಸಂಪಾದಿಸಿ",
    askPlaceholder: "ಹಲ್ಲಿನ ಸೂಕ್ಷ್ಮತೆಯ ಬಗ್ಗೆ ಕೇಳಿ...",
    quickQuestions: "ತ್ವರಿತ ಪ್ರಶ್ನೆಗಳು:",
    onlineStatus: "ಆನ್‌ಲೈನ್ - ವರ್ಚುವಲ್ ಸಹಾಯಕ"
  },

  ml: {
    dashboard: "ഡാഷ്‌ബോർഡ്",
    smartMirror: "സ്മാർട്ട് മിറർ",
    dentalChat: "ഡോ. മിന്റി ചാറ്റ്",
    profile: "പ്രൊഫൈൽ ക്രമീകരണങ്ങൾ",
    signOut: "സൈൻ ഔട്ട്",
    selectLanguage: "ഭാഷ തിരഞ്ഞെടുക്കുക",
    demographicsTitle: "നിങ്ങളെക്കുറിച്ച് പറയുക",
    demographicsSubtitle: "നിങ്ങളുടെ ദന്ത സംരക്ഷണം വ്യക്തിഗതമാക്കാൻ സഹായിക്കുക",
    fullNameLabel: "പൂർണ്ണ നാമം",
    fullNamePlaceholder: "പേര് നൽകുക",
    ageGroupLabel: "പ്രായവിഭാഗം",
    selectAgeGroup: "പ്രായവിഭാഗം തിരഞ്ഞെടുക്കുക",
    childMode: "12 വയസ്സിന് താഴെ",
    teenMode: "13-17 വയസ്സ്",
    adultMode: "18-59 വയസ്സ്",
    seniorMode: "60 വയസ്സിന് മുകളിൽ",
    genderLabel: "ലിംഗഭേദം",
    male: "പുരുഷൻ",
    female: "സ്ത്രീ",
    other: "മറ്റുള്ളവരുടേത്",
    continueBtn: "തുടരുക",
    savingProfile: "സേവ് ചെയ്യുന്നു...",
    step1of3: "ഘട്ടം 1 / 3",
    assessmentTitle: "ആരോഗ്യ വിലയിരുത്തൽ",
    question: "ചോദ്യം",
    of: "ൽ",
    completed: "പൂർത്തിയായി",
    nextQuestion: "അടുത്ത ചോദ്യം",
    prevQuestion: "മുമ്പത്തേത്",
    viewResults: "ഫലങ്ങൾ കാണുക",
    personalizedResult: "വ്യക്തിഗതമാക്കിയ ഫലം",
    prescriptionSummaryTitle: "ചികിത്സാ സംഗ്രഹം",
    whySuggestedTitle: "എന്തുകൊണ്ട് ഈ രീതി നിർദ്ദേശിച്ചു",
    basedOnAnswers: "നിങ്ങളുടെ മറുപടികളുടെ അടിസ്ഥാനത്തിൽ:",
    whatIsItTitle: "എന്താണ് ഈ രീതി?",
    howItWorksTitle: "ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നു",
    precautionsTitle: "മുൻകരുതലുകൾ",
    videoGuideTitle: "വീഡിയോ ഗൈഡ്",
    stepsTitle: "ഘട്ടം ഘട്ടമായുള്ള ഗൈഡ്",
    step: "ഘട്ടം",
    bestPracticeTitle: "മികച്ച രീതി",
    bestPracticeDesc: "ദിവസവും രണ്ടുനേരം 2 മിനിറ്റ് ബ്രഷ് ചെയ്യുക.",
    startMirrorBtn: "സ്മാർട്ട് മിറർ ആരംഭിക്കുക",
    returnDashboardBtn: "ഡാഷ്‌ബോർഡിലേക്ക് മടങ്ങുക",
    welcomeBack: "വീണ്ടും സ്വാഗതം",
    brushingStreak: "ബ്രഷിംഗ് സ്ട്രീക്ക്",
    daysStreak: "ദിവസങ്ങൾ",
    totalSessions: "ആകെ സെഷനുകൾ",
    weeklyCompliance: "പ്രതിവാര അനുസരണം",
    morningRoutine: "☀️ രാവിലത്തെ ശീലം",
    nightRoutine: "🌙 രാത്രിയിലെ ശീലം",
    saveReminders: "സമയം സേവ് ചെയ്യുക",
    retakeQuiz: "വീണ്ടും വിലയിരുത്തുക",
    editProfile: "എഡിറ്റ് ചെയ്യുക",
    askPlaceholder: "സംശയങ്ങൾ ചോദിക്കുക...",
    quickQuestions: "ചോദ്യങ്ങൾ:",
    onlineStatus: "ഓൺലൈൻ അസിസ്റ്റന്റ്"
  },

  mr: {
    dashboard: "डॅशबोर्ड",
    smartMirror: "स्मार्ट मिरर",
    dentalChat: "डॉ. मिंटी चॅट",
    profile: "प्रोफाइल सेटिंग्ज",
    signOut: "साइन आउट",
    selectLanguage: "भाषा निवडा",
    demographicsTitle: "आपल्याबद्दल सांगा",
    demographicsSubtitle: "तुमचा दंत काळजी अनुभव वैयक्तिकृत करण्यात मदत करा",
    fullNameLabel: "पूर्ण नाव",
    fullNamePlaceholder: "नाव प्रविष्ट करा",
    ageGroupLabel: "वयोगट",
    selectAgeGroup: "वयोगट निवडा",
    childMode: "१२ वर्षांखालील",
    teenMode: "१३-१७ वर्षे",
    adultMode: "१८-५९ वर्षे",
    seniorMode: "६०+ वर्षे",
    genderLabel: "लिंग",
    male: "पुरुष",
    female: "स्त्री",
    other: "इतर",
    continueBtn: "पुढे जा",
    savingProfile: "जतन करत आहे...",
    step1of3: "पायरी १ पैकी ३",
    assessmentTitle: "आरोग्य मूल्यमापन",
    question: "प्रश्न",
    of: "पैकी",
    completed: "पूर्ण झाले",
    nextQuestion: "पुढील प्रश्न",
    prevQuestion: "मागील",
    viewResults: "निकाल पहा",
    personalizedResult: "वैयक्तिक वैद्यकीय निकाल",
    prescriptionSummaryTitle: "वैद्यकीय सारांश",
    whySuggestedTitle: "ही पद्धत का सुचवली",
    basedOnAnswers: "तुमच्या उत्तरांच्या आधारे:",
    whatIsItTitle: "ही पद्धत काय आहे?",
    howItWorksTitle: "ही पद्धत कशी कार्य करते",
    precautionsTitle: "काळजी आणि सुरक्षितता",
    videoGuideTitle: "व्हिडिओ मार्गदर्शक",
    stepsTitle: "टप्प्याटप्प्याने मार्गदर्शक",
    step: "पायरी",
    bestPracticeTitle: "सर्वोत्तम सराव",
    bestPracticeDesc: "दिवसातून दोनदा २ मिनिटे ब्रश करा.",
    startMirrorBtn: "स्मार्ट मिरर सुरू करा",
    returnDashboardBtn: "डॅशबोर्डवर परत जा",
    welcomeBack: "पुन्हा स्वागत आहे",
    brushingStreak: "ब्रशिंग स्ट्राइक",
    daysStreak: "दिवस",
    totalSessions: "एकूण सत्रे",
    weeklyCompliance: "साप्ताहिक अनुपालन",
    morningRoutine: "☀️ सकाळची दिनचर्या",
    nightRoutine: "🌙 रात्रीची दिनचर्या",
    saveReminders: "वेळ जतन करा",
    retakeQuiz: "पुन्हा मूल्यमापन करा",
    editProfile: "संपादित करा",
    askPlaceholder: "प्रश्न विचारा...",
    quickQuestions: "प्रश्न:",
    onlineStatus: "ऑनलाइन सहाय्यक"
  },

  gu: {
    dashboard: "ડેશબોર્ડ",
    smartMirror: "સ્માર્ટ મિરર",
    dentalChat: "ડૉ. મિન્ટી ચેટ",
    profile: "પ્રોફાઇલ સેટિંગ્સ",
    signOut: "સાઇન આઉટ",
    selectLanguage: "ભાષા પસંદ કરો",
    demographicsTitle: "તમારા વિશે જણાવો",
    demographicsSubtitle: "તમારી ડેન્ટલ કેર અનુભવને વ્યક્તિગત કરવામાં મદદ કરો",
    fullNameLabel: "પૂરું નામ",
    fullNamePlaceholder: "નામ દાખલ કરો",
    ageGroupLabel: "ઉંમર જૂથ",
    selectAgeGroup: "ઉંમર જૂથ પસંદ કરો",
    childMode: "૧૨ વર્ષથી નીચે",
    teenMode: "૧૩-૧૭ વર્ષ",
    adultMode: "૧૮-૫૯ વર્ષ",
    seniorMode: "૬૦+ વર્ષ",
    genderLabel: "જાતિ",
    male: "પુરુષ",
    female: "સ્ત્રી",
    other: "અન્ય",
    continueBtn: "આગળ વધો",
    savingProfile: "સેવ થઈ રહ્યું છે...",
    step1of3: "પગલું ૧/૩",
    assessmentTitle: "ઓરલ હેલ્થ એસેસમેન્ટ",
    question: "પ્રશ્ન",
    of: "માંથી",
    completed: "પૂર્ણ થયું",
    nextQuestion: "આગળનો પ્રશ્ન",
    prevQuestion: "પાછળ",
    viewResults: "પરિણામો જુઓ",
    personalizedResult: "વ્યક્તિગત તબીબી પરિણામ",
    prescriptionSummaryTitle: "તબીબી સારાંશ",
    whySuggestedTitle: "આ પદ્ધતિ શા માટે સૂચવવામાં આવી",
    basedOnAnswers: "તમારા જવાબોના આધારે:",
    whatIsItTitle: "આ પદ્ધતિ શું છે?",
    howItWorksTitle: "આ પદ્ધતિ કેવી રીતે કામ કરે છે",
    precautionsTitle: "સાવચેતીઓ",
    videoGuideTitle: "વિડિઓ માર્ગદર્શિકા",
    stepsTitle: "પગલાંવાર માર્ગદર્શિકા",
    step: "પગલું",
    bestPracticeTitle: "શ્રેષ્ઠ સરાવ",
    bestPracticeDesc: "દિવસમાં બે વાર ૨ મિનિટ બ્રશ કરો.",
    startMirrorBtn: "સ્માર્ટ મિરર શરૂ કરો",
    returnDashboardBtn: "ડેશબોર્ડ પર પાછા જાઓ",
    welcomeBack: "સ્વાગત છે",
    brushingStreak: "બ્રશિંગ સ્ટ્રીક",
    daysStreak: "દિવસો",
    totalSessions: "કુલ સત્રો",
    weeklyCompliance: "સાપ્તાહિક પાલન",
    morningRoutine: "☀️ સવારની દિનચર્યા",
    nightRoutine: "🌙 રાત્રિની દિનચર્યા",
    saveReminders: "સમય સાચવો",
    retakeQuiz: "ફરીથી મૂલ્યાંકન કરો",
    editProfile: "એડિટ કરો",
    askPlaceholder: "પ્રશ્નો પૂછો...",
    quickQuestions: "પ્રશ્નો:",
    onlineStatus: "ઓનલાઇન સહાયક"
  },

  bn: {
    dashboard: "ড্যাশবোর্ড",
    smartMirror: "স্মার্ট মিরর",
    dentalChat: "ডঃ মিন্টি চ্যাট",
    profile: "প্রোফাইল সেটিংস",
    signOut: "সাইন আউট",
    selectLanguage: "ভাষা নির্বাচন করুন",
    demographicsTitle: "আপনার সম্পর্কে বলুন",
    demographicsSubtitle: "আপনার ডেন্টাল যত্ন অভিজ্ঞতা ব্যক্তিগত করতে সাহায্য করুন",
    fullNameLabel: "পূর্ণ নাম",
    fullNamePlaceholder: "নাম লিখুন",
    ageGroupLabel: "বয়স গোষ্ঠী",
    selectAgeGroup: "বয়স গোষ্ঠী নির্বাচন করুন",
    childMode: "১২ বছরের নিচে",
    teenMode: "১৩-১৭ বছর",
    adultMode: "১৮-৫৯ বছর",
    seniorMode: "৬০+ বছর",
    genderLabel: "লিঙ্গ",
    male: "পুরুষ",
    female: "মহিলা",
    other: "অন্যান্য",
    continueBtn: "চালিয়ে যান",
    savingProfile: "সংরক্ষণ করা হচ্ছে...",
    step1of3: "ধাপ ১ / ৩",
    assessmentTitle: "মৌখিক স্বাস্থ্য মূল্যায়ন",
    question: "প্রশ্ন",
    of: "এর",
    completed: "সম্পন্ন",
    nextQuestion: "পরবর্তী প্রশ্ন",
    prevQuestion: "পূর্ববর্তী",
    viewResults: "ফলাফল দেখুন",
    personalizedResult: "ব্যক্তিগতকৃত চিকিৎসা ফলাফল",
    prescriptionSummaryTitle: "চিকিৎসা প্রেসক্রিপশন সারসংক্ষেপ",
    whySuggestedTitle: "কেন এই পদ্ধতিটি সুপারিশ করা হয়েছে",
    basedOnAnswers: "আপনার উত্তরের ভিত্তিতে:",
    whatIsItTitle: "এই পদ্ধতিটি কী?",
    howItWorksTitle: "পদ্ধতিটি কীভাবে কাজ করে",
    precautionsTitle: "সতর্কতা এবং সুরক্ষা টিপস",
    videoGuideTitle: "ভিডিও ডেমো নির্দেশিকা",
    stepsTitle: "ধাপে ধাপে ব্রাশ করার নির্দেশিকা",
    step: "ধাপ",
    bestPracticeTitle: "সেরা অভ্যাস",
    bestPracticeDesc: "দিনে দুবার ২ মিনিট করে ব্রাশ করুন।",
    startMirrorBtn: "স্মার্ট মিরর শুরু করুন",
    returnDashboardBtn: "ড্যাশবোর্ডে ফিরে যান",
    welcomeBack: "স্বাগতম",
    brushingStreak: "ব্রাশ করার ধারাবাহিকতা",
    daysStreak: "দিন",
    totalSessions: "মোট সেশন",
    weeklyCompliance: "সাপ্তাহিক মেনে চলা",
    morningRoutine: "☀️ সকালের রুটিন",
    nightRoutine: "🌙 রাতের রুটিন",
    saveReminders: "সময় সংরক্ষণ করুন",
    retakeQuiz: "পুনরায় মূল্যায়ন করুন",
    editProfile: "সম্পাদনা করুন",
    askPlaceholder: "প্রশ্ন জিজ্ঞাসা করুন...",
    quickQuestions: "প্রশ্নাবলী:",
    onlineStatus: "অনলাইন সহকারী"
  },

  es: {
    dashboard: "Panel de Control",
    smartMirror: "Espejo Inteligente",
    dentalChat: "Chat Dr. Minty AI",
    profile: "Ajustes de Perfil",
    signOut: "Cerrar Sesión",
    selectLanguage: "Seleccionar Idioma",
    demographicsTitle: "Cuéntanos sobre ti",
    demographicsSubtitle: "Ayúdanos a personalizar tu experiencia de cuidado dental",
    fullNameLabel: "Nombre Completo",
    fullNamePlaceholder: "Ingresa tu nombre",
    ageGroupLabel: "Grupo de Edad",
    selectAgeGroup: "Selecciona grupo de edad",
    childMode: "Menor de 12 (Modo Niño)",
    teenMode: "13-17 (Adolescente)",
    adultMode: "18-59 (Modo Adulto)",
    seniorMode: "60+ (Adulto Mayor)",
    genderLabel: "Género",
    male: "Masculino",
    female: "Femenino",
    other: "Otro",
    continueBtn: "Continuar",
    savingProfile: "Guardando perfil...",
    step1of3: "Paso 1 de 3",
    assessmentTitle: "Evaluación de Salud Bucal",
    question: "Pregunta",
    of: "de",
    completed: "Completado",
    nextQuestion: "Siguiente Pregunta",
    prevQuestion: "Anterior",
    viewResults: "Ver Resultados Clínicos",
    personalizedResult: "Resultado Clínico Personalizado",
    prescriptionSummaryTitle: "Resumen de Prescripción Clínica",
    whySuggestedTitle: "Por qué se sugirió esta técnica para tus dientes",
    basedOnAnswers: "Basado en tus 10 respuestas:",
    whatIsItTitle: "¿Qué es esa técnica?",
    howItWorksTitle: "Cómo funciona la técnica",
    precautionsTitle: "Precauciones y Consejos de Seguridad",
    videoGuideTitle: "Guía de Demostración en Video",
    stepsTitle: "Guía de Cepillado Paso a Paso",
    step: "Paso",
    bestPracticeTitle: "Mejor Práctica Clínica",
    bestPracticeDesc: "Cepíllate durante 2 minutos dos veces al día.",
    startMirrorBtn: "Iniciar Sesión de Espejo Inteligente",
    returnDashboardBtn: "Volver al Panel",
    welcomeBack: "Bienvenido de nuevo",
    brushingStreak: "Racha de Cepillado",
    daysStreak: "Días de Racha",
    totalSessions: "Sesiones Totales",
    weeklyCompliance: "Cumplimiento Semanal",
    morningRoutine: "☀️ Rutina Matutina",
    nightRoutine: "🌙 Rutina Nocturna",
    saveReminders: "Guardar Horarios",
    retakeQuiz: "Volver a realizar evaluación",
    editProfile: "Editar Detalles del Perfil",
    askPlaceholder: "Pregunta sobre sensibilidad o pasta...",
    quickQuestions: "Preguntas rápidas:",
    onlineStatus: "En línea - Asistente Virtual"
  },

  fr: {
    dashboard: "Tableau de Bord",
    smartMirror: "Miroir Intelligent",
    dentalChat: "Chat Dr. Minty AI",
    profile: "Paramètres de Profil",
    signOut: "Se Déconnecter",
    selectLanguage: "Choisir la Langue",
    demographicsTitle: "Parlez-nous de vous",
    demographicsSubtitle: "Aidez-nous à personnaliser votre expérience dentaire",
    fullNameLabel: "Nom Complet",
    fullNamePlaceholder: "Entrez votre nom",
    ageGroupLabel: "Tranche d'âge",
    selectAgeGroup: "Sélectionnez la tranche d'âge",
    childMode: "Moins de 12 ans (Enfant)",
    teenMode: "13-17 ans (Adolescent)",
    adultMode: "18-59 ans (Adulte)",
    seniorMode: "60+ ans (Senior)",
    genderLabel: "Genre",
    male: "Homme",
    female: "Femme",
    other: "Autre",
    continueBtn: "Continuer",
    savingProfile: "Enregistrement...",
    step1of3: "Étape 1 sur 3",
    assessmentTitle: "Évaluation de la Santé Bucco-Dentaire",
    question: "Question",
    of: "sur",
    completed: "Terminé",
    nextQuestion: "Question Suivante",
    prevQuestion: "Précédent",
    viewResults: "Voir les Résultats",
    personalizedResult: "Résultat Clinique Personnalisé",
    prescriptionSummaryTitle: "Résumé de la Prescription",
    whySuggestedTitle: "Pourquoi cette technique a été suggérée",
    basedOnAnswers: "Basé sur vos 10 réponses:",
    whatIsItTitle: "Quelle est cette technique?",
    howItWorksTitle: "Comment fonctionne la technique",
    precautionsTitle: "Précautions et Conseils de Sécurité",
    videoGuideTitle: "Guide de Démonstration Vidéo",
    stepsTitle: "Guide de Brossage Étape par Étape",
    step: "Étape",
    bestPracticeTitle: "Meilleure Pratique Clinique",
    bestPracticeDesc: "Brossez-vous les dents pendant 2 minutes deux fois par jour.",
    startMirrorBtn: "Démarrer le Miroir Intelligent",
    returnDashboardBtn: "Retour au Tableau de Bord",
    welcomeBack: "Bon retour",
    brushingStreak: "Série de Brossage",
    daysStreak: "Jours Consécutifs",
    totalSessions: "Sessions Totales",
    weeklyCompliance: "Observance Hebdomadaire",
    morningRoutine: "☀️ Routine du Matin",
    nightRoutine: "🌙 Routine du Soir",
    saveReminders: "Enregistrer les Rappels",
    retakeQuiz: "Refaire l'Évaluation",
    editProfile: "Modifier le Profil",
    askPlaceholder: "Posez une question sur le brossage...",
    quickQuestions: "Questions rapides:",
    onlineStatus: "En ligne - Assistant Virtuel"
  },

  de: {
    dashboard: "Dashboard",
    smartMirror: "Smart Spiegel",
    dentalChat: "Dr. Minty KI Chat",
    profile: "Profileinstellungen",
    signOut: "Abmelden",
    selectLanguage: "Sprache Wählen",
    demographicsTitle: "Erzählen Sie uns von sich",
    demographicsSubtitle: "Helfen Sie uns, Ihre Zahnpflege zu personalisieren",
    fullNameLabel: "Vollständiger Name",
    fullNamePlaceholder: "Geben Sie Ihren Namen ein",
    ageGroupLabel: "Altersgruppe",
    selectAgeGroup: "Altersgruppe auswählen",
    childMode: "Unter 12 Jahre (Kinder-Modus)",
    teenMode: "13-17 Jahre (Teenie)",
    adultMode: "18-59 Jahre (Erwachsene)",
    seniorMode: "60+ Jahre (Senioren)",
    genderLabel: "Geschlecht",
    male: "Männlich",
    female: "Weiblich",
    other: "Divers",
    continueBtn: "Weiter",
    savingProfile: "Speichern...",
    step1of3: "Schritt 1 von 3",
    assessmentTitle: "Mundgesundheitsbewertung",
    question: "Frage",
    of: "von",
    completed: "Abgeschlossen",
    nextQuestion: "Nächste Frage",
    prevQuestion: "Zurück",
    viewResults: "Klinische Ergebnisse Anzeigen",
    personalizedResult: "Personalisiertes Klinisches Ergebnis",
    prescriptionSummaryTitle: "Klinische Rezeptzusammenfassung",
    whySuggestedTitle: "Warum diese Technik empfohlen wurde",
    basedOnAnswers: "Basierend auf Ihren 10 Antworten:",
    whatIsItTitle: "Was ist diese Technik?",
    howItWorksTitle: "Wie die Technik funktioniert",
    precautionsTitle: "Vorsichtsmaßnahmen & Sicherheitstipps",
    videoGuideTitle: "Video-Demonstrationsanleitung",
    stepsTitle: "Schritt-für-Schritt Putzanleitung",
    step: "Schritt",
    bestPracticeTitle: "Klinische Best Practice",
    bestPracticeDesc: "Putzen Sie zweimal täglich 2 Minuten lang Ihre Zähne.",
    startMirrorBtn: "Smart Spiegel Starten",
    returnDashboardBtn: "Zurück zum Dashboard",
    welcomeBack: "Willkommen zurück",
    brushingStreak: "Putz-Serie",
    daysStreak: "Tage Serie",
    totalSessions: "Gesamte Sitzungen",
    weeklyCompliance: "Wöchentliche Einhaltung",
    morningRoutine: "☀️ Morgenroutine",
    nightRoutine: "🌙 Abendroutine",
    saveReminders: "Erinnerung Speichern",
    retakeQuiz: "Bewertung Wiederholen",
    editProfile: "Profil Bearbeiten",
    askPlaceholder: "Fragen Sie Dr. Minty...",
    quickQuestions: "Schnellfragen:",
    onlineStatus: "Online - Virtueller Assistent"
  }
};

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  t: Record<string, string>;
  currentLangObj: LanguageOption;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState(() => localStorage.getItem("appLanguage") || "en");

  const setLanguage = (lang: string) => {
    setLanguageState(lang);
    localStorage.setItem("appLanguage", lang);
  };

  const activeTranslations = globalTranslations[language] || globalTranslations.en;
  
  // Safe string translation getter fallback using Proxy
  const t = new Proxy(activeTranslations, {
    get: (target, prop: string) => {
      if (prop in target) return target[prop];
      return globalTranslations.en[prop] || prop;
    }
  });

  const currentLangObj = supportedLanguages.find(l => l.code === language) || supportedLanguages[0];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, currentLangObj }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within a LanguageProvider");
  return context;
}